<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260101000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users (with 2FA columns + role), password_reset_tokens, posts on PostgreSQL.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->isPostgreSql(),
            'Migration can only be executed on PostgreSQL.'
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                role_id SMALLINT NOT NULL DEFAULT 1,
                email VARCHAR(255) NOT NULL,
                email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                password VARCHAR(255) NOT NULL,
                two_factor_secret TEXT DEFAULT NULL,
                two_factor_recovery_codes TEXT DEFAULT NULL,
                two_factor_confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                remember_token VARCHAR(100) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX users_email_unique ON users (email)');
        $this->addSql("COMMENT ON COLUMN users.email_verified_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN users.two_factor_confirmed_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN users.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN users.updated_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql(<<<'SQL'
            CREATE TABLE password_reset_tokens (
                email VARCHAR(255) NOT NULL,
                token VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (email)
            )
        SQL);
        $this->addSql("COMMENT ON COLUMN password_reset_tokens.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql(<<<'SQL'
            CREATE TABLE posts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id BIGINT NOT NULL,
                title VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_posts_user_id ON posts (user_id)');
        $this->addSql("COMMENT ON COLUMN posts.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN posts.updated_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_posts_user FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->isPostgreSql(),
            'Migration can only be executed on PostgreSQL.'
        );

        $this->addSql('ALTER TABLE posts DROP CONSTRAINT FK_posts_user');
        $this->addSql('DROP TABLE posts');
        $this->addSql('DROP TABLE password_reset_tokens');
        $this->addSql('DROP TABLE users');
    }

    private function isPostgreSql(): bool
    {
        return $this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform;
    }
}
