<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260513000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create site_translation table for UI strings (alias + language + text).';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->isPostgreSql(),
            'Migration can only be executed on PostgreSQL.'
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE site_translation (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                alias VARCHAR(190) NOT NULL,
                language_type VARCHAR(3) NOT NULL,
                translate TEXT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_site_translation_alias_language ON site_translation (alias, language_type)');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->isPostgreSql(),
            'Migration can only be executed on PostgreSQL.'
        );

        $this->addSql('DROP TABLE IF EXISTS site_translation');
    }

    private function isPostgreSql(): bool
    {
        return $this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform;
    }
}
