<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260512000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add posts.content text column and create comments + post_likes tables.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->isPostgreSql(),
            'Migration can only be executed on PostgreSQL.'
        );

        $this->addSql("ALTER TABLE posts ADD COLUMN IF NOT EXISTS content TEXT NOT NULL DEFAULT ''");

        $this->addSql(<<<'SQL'
            CREATE TABLE comments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                post_id BIGINT NOT NULL,
                user_id BIGINT NOT NULL,
                body TEXT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_comments_post_id ON comments (post_id)');
        $this->addSql('CREATE INDEX IDX_comments_user_id ON comments (user_id)');
        $this->addSql("COMMENT ON COLUMN comments.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_comments_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_comments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql(<<<'SQL'
            CREATE TABLE post_likes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                post_id BIGINT NOT NULL,
                user_id BIGINT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_post_likes_post_user ON post_likes (post_id, user_id)');
        $this->addSql("COMMENT ON COLUMN post_likes.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE post_likes ADD CONSTRAINT FK_post_likes_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE post_likes ADD CONSTRAINT FK_post_likes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->isPostgreSql(),
            'Migration can only be executed on PostgreSQL.'
        );

        $this->addSql('ALTER TABLE post_likes DROP CONSTRAINT IF EXISTS FK_post_likes_user');
        $this->addSql('ALTER TABLE post_likes DROP CONSTRAINT IF EXISTS FK_post_likes_post');
        $this->addSql('DROP TABLE IF EXISTS post_likes');

        $this->addSql('ALTER TABLE comments DROP CONSTRAINT IF EXISTS FK_comments_user');
        $this->addSql('ALTER TABLE comments DROP CONSTRAINT IF EXISTS FK_comments_post');
        $this->addSql('DROP TABLE IF EXISTS comments');

        $this->addSql('ALTER TABLE posts DROP COLUMN IF EXISTS content');
    }

    private function isPostgreSql(): bool
    {
        return $this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform;
    }
}
