<?php

declare(strict_types=1);

namespace App\SiteUi;

/**
 * Default English copy for initial DB seed (all languages get this text until edited in admin).
 */
final class SiteUiDefaults
{
    /** @var array<string, string> */
    public const ALIASES = [
        // Meta & chrome
        'meta.feed_title' => 'Blogosphere — feed',
        'aria.close' => 'Close',
        'aria.toggle_nav' => 'Toggle navigation',

        // Feed / posts page (UI only — not post body/title)
        'nav.brand' => 'Blogosphere',
        'nav.admin' => 'Admin',
        'nav.new_post' => 'New post',
        'nav.logout' => 'Log out',
        'nav.account' => 'My account',
        'nav.feed' => 'Feed',
        'feed.title' => 'Posts feed',
        'feed.subtitle' => 'Share thoughts, leave reactions and comments',
        'feed.search_placeholder' => 'Search posts...',
        'feed.unknown_author' => 'Unknown',
        'feed.edit' => 'Edit',
        'feed.delete' => 'Delete',
        'feed.delete_post_confirm' => 'Delete this post permanently?',
        'feed.comments_suffix' => 'comments',
        'feed.comments_heading' => 'Comments',
        'feed.no_comments' => 'No comments yet. Be the first!',
        'feed.delete_comment_confirm' => 'Delete this comment?',
        'feed.comment_placeholder' => 'Write a comment...',
        'feed.send' => 'Send',
        'feed.empty_search' => 'Nothing found for "%query%"',
        'feed.empty_no_posts' => 'No posts yet',
        'feed.empty_try_different' => 'Try a different search query.',
        'feed.empty_be_first' => 'Be the first to publish something.',
        'feed.create_post' => 'Create post',
        'modal.create_new_post' => 'Create new post',
        'modal.edit_post' => 'Edit post',
        'label.title' => 'Title',
        'label.title_required' => 'Title',
        'label.content' => 'Content',
        'modal.title_placeholder' => 'What do you want to share?',
        'modal.content_placeholder' => 'Post body...',
        'modal.create_hint' => 'After publishing you can react to and comment on your post.',
        'modal.cancel' => 'Cancel',
        'modal.publish' => 'Publish',
        'modal.save_changes' => 'Save changes',

        // Auth layout
        'auth.brand_title' => 'NatureAuth',
        'auth.brand_tagline' => 'eco-friendly login · clean signup',
        'auth.page_title' => 'Login / Sign Up',

        // Login
        'login.welcome_back' => 'Welcome back!',
        'login.email_ph' => 'Enter your email',
        'login.password_ph' => 'Password',
        'login.remember_me' => 'Remember me',
        'login.submit' => 'Log in',
        'login.or_continue' => 'or continue with',
        'login.forgot' => 'Forgot password?',
        'login.no_account' => 'No account?',
        'login.show_password' => 'Show password',

        // Register
        'register.title' => 'Create account',
        'register.username_ph' => 'Choose username',
        'register.email_ph' => 'Email address',
        'register.password_ph' => 'Create password (min. 8 chars)',
        'register.confirm_ph' => 'Confirmation password',
        'register.agree' => 'I agree to the terms and conditions',
        'register.submit' => 'Sign up',
        'register.or_signup' => 'or sign up with',
        'register.already_have' => 'Already have an account?',
        'register.privacy' => 'Privacy policy',

        // Forgot / reset / 2FA
        'forgot.title' => 'Reset password',
        'forgot.intro' => 'Enter your email and we\'ll send you a link to reset your password.',
        'forgot.submit' => 'Send reset link',
        'forgot.back_login' => 'Back to login',
        'reset.title' => 'Set new password',
        'reset.intro' => 'Enter your new password below.',
        'reset.new_password_ph' => 'New password (min. 8 chars)',
        'reset.confirm_ph' => 'Confirm new password',
        'reset.submit' => 'Reset password',
        'reset.back_login' => 'Back to login',
        'twofa.title' => 'Two-factor authentication',
        'twofa.intro' => 'Enter the 6-digit code from your authenticator app.',
        'twofa.placeholder' => '123 456',
        'twofa.verify' => 'Verify',
        'twofa.cancel' => 'Cancel',

        // Account
        'account.page_title' => 'My account',
        'account.heading' => 'Personal dashboard',
        'account.posts.title' => 'My posts',
        'account.posts.empty' => 'You have not published any posts yet.',
        'account.posts.open_feed' => 'Open in feed',
        'account.posts.meta' => 'Posted',
        'account.profile.title' => 'Profile',
        'account.profile.email_note' => 'Email cannot be changed.',
        'account.field.display_name' => 'Display name',
        'account.field.email' => 'Email',
        'account.btn.save_profile' => 'Save profile',
        'account.password.title' => 'Change password',
        'account.field.current_password' => 'Current password',
        'account.field.new_password' => 'New password',
        'account.field.repeat_password' => 'Repeat new password',
        'account.btn.change_password' => 'Update password',
        'account.flash.profile_saved' => 'Profile updated.',
        'account.flash.profile_invalid' => 'Please enter a valid display name.',
        'account.flash.password_changed' => 'Password updated.',
        'account.flash.password_invalid' => 'Please check the password fields.',
        'account.flash.wrong_password' => 'Current password is incorrect.',

        // Flash messages (controllers)
        'flash.invalid_csrf' => 'Invalid CSRF token.',
        'flash.title_empty' => 'Title cannot be empty.',
        'flash.post_published' => 'Post published.',
        'flash.post_updated' => 'Post updated.',
        'flash.post_removed' => 'Post removed.',
        'flash.comment_empty' => 'Comment cannot be empty.',
        'flash.comment_removed' => 'Comment removed.',
        'flash.email_taken' => 'The email has already been taken.',
        'flash.account_created' => 'Account created. Please sign in.',
        'flash.password_reset_sent' => 'We have emailed your password reset link!',
        'flash.password_reset_invalid_token' => 'This password reset token is invalid.',
        'flash.user_not_found' => 'User not found.',
        'flash.password_reset_done' => 'Your password has been reset!',
        'flash.user_deleted' => 'User "%name%" deleted.',
        'flash.post_deleted' => 'Post "%title%" deleted.',
        'flash.posts_bulk_deleted' => 'Deleted %count% post(s).',
        'flash.posts_bulk_none' => 'No posts were deleted.',
        'flash.translation_deleted' => 'Translation "%alias%" (%lang%) deleted.',

        // Admin chrome
        'admin.nav.blog_admin' => 'Blog Admin',
        'admin.nav.logged_in_as' => 'Logged in as',
        'admin.nav.dashboard' => 'Dashboard',
        'admin.nav.home' => 'Home',
        'admin.nav.content' => 'Content',
        'admin.nav.users' => 'Users',
        'admin.nav.posts' => 'Posts',
        'admin.nav.translations' => 'Translations',
        'admin.footer.note' => 'Blog Admin Panel — green-on-white theme',
        'admin.footer.dashboard' => 'Dashboard',
        'admin.footer.home' => 'Home',
        'admin.topbar.new_post' => 'New post',
        'admin.topbar.new_user' => 'New user',
        'admin.users.title' => 'Users',
        'admin.users.add' => 'Add User',
        'admin.users.search_ph' => 'Search by name or email...',
        'admin.filter.all_users' => 'All users',
        'admin.filter.2fa_confirmed' => '2FA confirmed',
        'admin.filter.2fa_null' => '2FA not confirmed (Null)',
        'admin.table.id' => 'ID',
        'admin.table.name' => 'Name',
        'admin.table.email' => 'Email address',
        'admin.table.2fa' => '2FA confirmed',
        'admin.table.actions' => 'Actions',
        'admin.users.empty' => 'No users found.',
        'admin.users.confirmed' => 'Confirmed',
        'admin.users.null_badge' => 'Null',
        'admin.action.edit_user' => 'Edit user',
        'admin.action.delete_user' => 'Delete user',
        'admin.action.edit_post' => 'Edit post',
        'admin.action.delete_post' => 'Delete post',
        'admin.posts.title' => 'Posts',
        'admin.posts.add' => 'Add Post',
        'admin.posts.bulk_delete' => 'Delete',
        'admin.posts.search_ph' => 'Search by title or author...',
        'admin.posts.table.title' => 'Title',
        'admin.posts.table.author' => 'Author',
        'admin.posts.table.status' => 'Status',
        'admin.posts.table.created' => 'Created',
        'admin.posts.empty' => 'No results found.',
        'admin.posts.create_first' => 'Create the first post',
        'admin.translations.title' => 'Translations',
        'admin.translations.all_label' => 'All translations',
        'admin.translations.search_ph' => 'Search by alias or translation...',
        'admin.translations.add' => 'Add translation',
        'admin.translations.export' => 'Export',
        'admin.translations.footer_line' => 'Blog Admin Panel — Translations manager',
        'admin.translations.results_badge' => '%count% results',
        'admin.translations.range' => 'Showing %first%–%last% of %total% results',
        'admin.translations.empty' => 'No translations found.',
        'admin.pagination.previous' => 'Previous',
        'admin.pagination.next' => 'Next',
        'admin.filter.all_languages' => 'All languages',
        'admin.table.alias' => 'Alias',
        'admin.table.translation' => 'Translation',
        'admin.table.language' => 'Language',
        'admin.action.edit_translation' => 'Edit translation',
        'admin.action.delete_translation' => 'Delete translation',
        'admin.dashboard.title' => 'Dashboard',
        'admin.dashboard.users_card' => 'Users',
        'admin.dashboard.users_total_hint' => 'Total registered users',
        'admin.dashboard.with_2fa' => 'With 2FA',
        'admin.dashboard.ga_confirmed' => 'Confirmed Google Authenticator',
        'admin.dashboard.posts_card' => 'Posts',
        'admin.dashboard.posts_total_hint' => 'Total published posts',
        'admin.dashboard.new_this_week' => 'New this week · Posts created in last 7 days',
        'admin.dashboard.latest_posts' => 'Latest posts',
        'admin.dashboard.view_all' => 'View all',
        'admin.dashboard.no_posts' => 'No posts yet.',
        'admin.dashboard.start_blog' => 'Start blogging by creating your first post.',
        'admin.dashboard.create_first_post' => 'Create the first post',
        'admin.dashboard.latest_users' => 'Latest users',
        'admin.status.published' => 'Published',
        'admin.status.draft' => 'Draft',
        'admin.guest' => 'guest',
        'admin.version_badge' => 'v2.0 · Green Panel',
        'admin.search.apply' => 'Apply',
        'admin.search.results_footer' => '%count% result(s)',

        // Layout / default navbar (if used)
        'layout.nav.registration' => 'Registration',
        'layout.nav.login' => 'Login',
        'layout.nav.create_post' => 'Create post',
    ];

    private function __construct()
    {
    }
}
